#pragma once

#include <SDL3/SDL_log.h>

typedef enum: int
{
	LOG_CATEGORY_CORE = SDL_LOG_CATEGORY_CUSTOM,
	LOG_CATEGORY_RENDER,
	LOG_CATEGORY_FONT,
	LOG_CATEGORY_ASSETS,
	LOG_CATEGORY_INPUT,
	LOG_CATEGORY_PHYSICS,
	LOG_CATEGORY_MODEL,
	LOG_CATEGORY_ECS,
	LOG_CATEGORY_SCRIPT,
	LOG_CATEGORY_UI,
} log_category_t;
