name: BSD

on: [ push, pull_request ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    name: '${{ matrix.os-type }}-${{ matrix.arch }}'
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: cpa.sh {0}

    strategy:
      matrix:
        include:
          - os-type: 'freebsd'
            os-version: '15.1'
            arch: 'x86-64'
            compile-flags: '-march=x86-64-v3'

          - os-type: 'freebsd'
            os-version: '15.1'
            arch: 'arm64'

          - os-type: 'openbsd'
            os-version: '7.9'
            arch: 'x86-64'
            compile-flags: '-march=x86-64-v3'

          - os-type: 'openbsd'
            os-version: '7.9'
            arch: 'arm64'

          - os-type: 'netbsd'
            os-version: '10.1'
            arch: 'x86-64'
            compile-flags: '-march=x86-64-v3'

          - os-type: 'netbsd'
            os-version: '10.1'
            arch: 'arm64'

    steps:
      - uses: actions/checkout@v5

      - name: Start VM
        uses: cross-platform-actions/action@v1.3.0
        with:
          operating_system: '${{ matrix.os-type }}'
          version: '${{ matrix.os-version }}'
          architecture: '${{ matrix.arch }}'

      - name: Install Dependencies
        if: ${{ matrix.os-type == 'freebsd' }}
        run: sudo pkg install -y git cmake sdl3

      - name: Install Dependencies
        if: ${{ matrix.os-type == 'openbsd' }}
        run: sudo pkg_add -I git cmake sdl3

      - name: Install Dependencies
        if: ${{ matrix.os-type == 'netbsd' }}
        run: sudo pkgin -y install git cmake SDL3

      - name: Configure CMake
        run: cmake -S . -B build -D ENABLE_TESTS=ON -D CMAKE_BUILD_TYPE=$BUILD_TYPE -D CMAKE_C_FLAGS="${{ matrix.compile-flags }}" -D CMAKE_CXX_FLAGS="${{ matrix.compile-flags }}"

      - name: Build
        run: cmake --build build

      - name: Test
        run: ctest --extra-verbose --test-dir build/tests
