name: Windows

on: [ push, pull_request ]

env:
  BUILD_TYPE: Release
  CMAKE_GENERATOR: "Ninja"

jobs:
  build:
    name: '${{ matrix.arch }}'
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        include:
          - os: windows-latest
            arch: 'x86_64'
            compile-flags: '-march=x86-64-v3'

          - os: windows-11-arm
            arch: 'arm64'
            compiler-flags: '-mfloat-abi=hard -mfpu=neon'

    steps:
      - uses: actions/checkout@v5

      - name: Set up scoop
        shell: pwsh
        run: |
          irm get.scoop.sh | iex
          exit $LASTEXITCODE

      - name: Set up compiler (x86_64)
        if: ${{ matrix.arch == 'x86_64' }}
        shell: pwsh
        run: scoop install llvm

      - name: Set up compiler (arm64)
        if: ${{ matrix.arch == 'arm64' }}
        shell: pwsh
        run: scoop install llvm-arm64

      - name: Configure CMake
        run: cmake -S . -B build -G "${{env.CMAKE_GENERATOR}}" -D CMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -D CMAKE_C_FLAGS="${{matrix.compile-flags}}" -D CMAKE_CXX_FLAGS="${{matrix.compile-flags}}"

      - name: Build
        run: cmake --build build

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: chirp3d-windows-${{ matrix.arch }}
          path: |
            ${{runner.workspace}}\chirp3d\build\chirp3d.exe
            ${{runner.workspace}}\chirp3d\build\SDL3.dll
